# Generated by Django 5.0 on 2023-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
